### ISSUE TITLE
Fail to load

### ISSUE THREAD

**Issue by Superelmanu** [mmhobi7/obsidian-autoview#1]
Installed manual, failed to load in Obsidian.

**Comment by mmhobi7** [comment]
I'm going to need more details, but just to ensure, you went to your plugins folder in your .obsidian and followed [this](https://github.com/mmhobi7/obsidian-autoview#local-installation) correct?

**Comment by Superelmanu** [comment]
I was unaware that I had to compile it in TypeScript. I never use TypeScript. I may be better off waiting for your official release?

**Comment by DutchPete** [comment]
@Superelmanu go to the “home” page: https://github.com/mmhobi7/obsidian-autoview.
Then, on the right you'll see *Releases*, click on latest, from there download `main.js` and `manifest.json`.

Manually transfer them to the Autoview subfolder in the plug-ins folder in `.obsidian`.
Then refreh Obsidian.
