### ISSUE TITLE
Ignore certain keyboard keys? 

### ISSUE THREAD

**Issue by MartynKeigher** [mmhobi7/obsidian-autoview#4]
Is there any way that the **Ctrl, Alt, Shift, Tab, Escape** & **Space** keyboard keys can be ignored by this plugin? Or can we have configurable options for this plugin, so that I could modify it to only accept 'a-z' keystrokes as key's to trigger the edit mode?

Reason: I use shortcuts **_a lot_** & each time I try to use one, while the shortcut does work... its incredibly disorientating to have the page, flip back to edit mode when I had no intention of editing the page.

Thanks. 
://mk

**Comment by mmhobi7** [comment]
Yea ez, I'm hesitant on the a-z cause different languages but eh I'll throw
it in the options
